# Generated by Django 5.2.17 on 2026-09-03 14:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('nickname', models.CharField(blank=True, max_length=60, verbose_name='apelido')),
                ('bio', models.TextField(blank=True, verbose_name='biografia')),
                ('specialties', models.JSONField(blank=True, default=list, help_text='Lista de textos livres, ex.: ["Degradê", "Barba terapia"]', verbose_name='especialidades')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='percentual de comissão')),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='avaliação média')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='total de avaliações')),
                ('hired_at', models.DateField(blank=True, null=True, verbose_name='data de admissão')),
                ('branches', models.ManyToManyField(help_text='Filiais em que o barbeiro atende.', related_name='barbers', to='branches.branch', verbose_name='filiais')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'barbeiro',
                'verbose_name_plural': 'barbeiros',
                'ordering': ('user__first_name',),
            },
        ),
        migrations.CreateModel(
            name='BarberService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço personalizado')),
                ('custom_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='duração personalizada (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='barbers.barber', verbose_name='barbeiro')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='services.service', verbose_name='serviço')),
            ],
            options={
                'verbose_name': 'serviço do barbeiro',
                'verbose_name_plural': 'serviços do barbeiro',
                'ordering': ('barber', 'service'),
            },
        ),
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='barbers', through='barbers.BarberService', to='services.service', verbose_name='serviços'),
        ),
        migrations.CreateModel(
            name='SpecialWorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='data')),
                ('starts_at', models.TimeField(verbose_name='início')),
                ('ends_at', models.TimeField(verbose_name='fim')),
                ('break_starts_at', models.TimeField(blank=True, null=True, verbose_name='início do intervalo')),
                ('break_ends_at', models.TimeField(blank=True, null=True, verbose_name='fim do intervalo')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_hours', to='barbers.barber', verbose_name='barbeiro')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_hours', to='branches.branch', verbose_name='filial')),
            ],
            options={
                'verbose_name': 'horário especial',
                'verbose_name_plural': 'horários especiais',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('type', models.CharField(choices=[('VACATION', 'Férias'), ('DAY_OFF', 'Folga'), ('HOLIDAY', 'Feriado'), ('BLOCK', 'Bloqueio de agenda'), ('SICK_LEAVE', 'Atestado'), ('OTHER', 'Outro')], default='BLOCK', max_length=12, verbose_name='tipo')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='início')),
                ('ends_at', models.DateTimeField(db_index=True, verbose_name='fim')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='motivo')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='barbers.barber', verbose_name='barbeiro')),
                ('branch', models.ForeignKey(blank=True, help_text='Em branco = ausência em todas as filiais.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='branches.branch', verbose_name='filial')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_time_offs', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'ausência',
                'verbose_name_plural': 'ausências',
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='dia da semana')),
                ('starts_at', models.TimeField(verbose_name='início')),
                ('ends_at', models.TimeField(verbose_name='fim')),
                ('break_starts_at', models.TimeField(blank=True, null=True, verbose_name='início do intervalo')),
                ('break_ends_at', models.TimeField(blank=True, null=True, verbose_name='fim do intervalo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='barbers.barber', verbose_name='barbeiro')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='branches.branch', verbose_name='filial')),
            ],
            options={
                'verbose_name': 'horário de trabalho',
                'verbose_name_plural': 'horários de trabalho',
                'ordering': ('barber', 'weekday', 'starts_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='barberservice',
            constraint=models.UniqueConstraint(fields=('barber', 'service'), name='unique_barberservice_barber_service'),
        ),
        migrations.AddConstraint(
            model_name='specialworkinghour',
            constraint=models.UniqueConstraint(fields=('barber', 'branch', 'date'), name='unique_specialhour_barber_branch_date'),
        ),
        migrations.AddConstraint(
            model_name='specialworkinghour',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='specialhour_ends_after_starts'),
        ),
        migrations.AddIndex(
            model_name='timeoff',
            index=models.Index(fields=['barber', 'starts_at', 'ends_at'], name='barbers_tim_barber__909bad_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeoff',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='timeoff_ends_after_starts'),
        ),
        migrations.AddIndex(
            model_name='workinghour',
            index=models.Index(fields=['barber', 'weekday', 'is_active'], name='barbers_wor_barber__13e20e_idx'),
        ),
        migrations.AddConstraint(
            model_name='workinghour',
            constraint=models.UniqueConstraint(fields=('barber', 'branch', 'weekday'), name='unique_workinghour_barber_branch_weekday'),
        ),
        migrations.AddConstraint(
            model_name='workinghour',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='workinghour_ends_after_starts'),
        ),
    ]
