# Generated by Django 5.2.17 on 2026-09-03 14:26

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('first_name', models.CharField(max_length=80, verbose_name='nome')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='sobrenome')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='telefone')),
                ('role', models.CharField(choices=[('OWNER', 'Proprietário'), ('BARBER', 'Barbeiro'), ('CLIENT', 'Cliente')], db_index=True, default='CLIENT', max_length=10, verbose_name='perfil')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.user_avatar_path, verbose_name='avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verificado')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acesso ao admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ('first_name', 'last_name'),
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token de redefinição de senha',
                'verbose_name_plural': 'tokens de redefinição de senha',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
    ]
