# Generated by Django 5.2.17 on 2026-09-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='ID da conta Google'),
        ),
    ]
