[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = test_*.py
testpaths = apps
addopts =
    --strict-markers
    --disable-warnings
    -ra
    --ds=config.settings.test
markers =
    slow: testes mais demorados
filterwarnings =
    ignore::DeprecationWarning
