# Generated by Django 5.2.17 on 2026-09-03 14:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('barbers', '0001_initial'),
        ('branches', '0001_initial'),
        ('inventory', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], db_index=True, max_length=8, verbose_name='tipo')),
                ('category', models.CharField(choices=[('SERVICES', 'Serviços'), ('PRODUCTS', 'Produtos'), ('SALARY', 'Salários'), ('COMMISSION', 'Comissões'), ('RENT', 'Aluguel'), ('ELECTRICITY', 'Energia elétrica'), ('WATER', 'Água'), ('INTERNET', 'Internet'), ('SUPPLIES', 'Insumos'), ('MARKETING', 'Marketing'), ('TAXES', 'Impostos'), ('OTHER', 'Outros')], db_index=True, default='OTHER', max_length=15, verbose_name='categoria')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor')),
                ('date', models.DateField(db_index=True, verbose_name='data')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('is_automatic', models.BooleanField(default=False, help_text='Lançamentos criados pelo sistema a partir de atendimentos/vendas.', verbose_name='gerado automaticamente')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='appointments.appointment', verbose_name='agendamento')),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='barbers.barber', verbose_name='barbeiro')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='branches.branch', verbose_name='filial')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.payment', verbose_name='pagamento')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.sale', verbose_name='venda')),
            ],
            options={
                'verbose_name': 'lançamento financeiro',
                'verbose_name_plural': 'lançamentos financeiros',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor base')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='percentual')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor da comissão')),
                ('reference_date', models.DateField(db_index=True, verbose_name='data de referência')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Paga'), ('CANCELLED', 'Cancelada')], db_index=True, default='PENDING', max_length=10, verbose_name='status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paga em')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='appointments.appointment', verbose_name='agendamento')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='barbers.barber', verbose_name='barbeiro')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='branches.branch', verbose_name='filial')),
                ('sale_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='inventory.saleitem', verbose_name='item de venda')),
                ('payout_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payouts', to='finance.transaction', verbose_name='lançamento de pagamento')),
            ],
            options={
                'verbose_name': 'comissão',
                'verbose_name_plural': 'comissões',
                'ordering': ('-reference_date', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['branch', 'date', 'type'], name='finance_tra_branch__03b32c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'category', 'date'], name='finance_tra_type_e675aa_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['barber', 'reference_date', 'status'], name='finance_com_barber__9cdcb8_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['branch', 'status'], name='finance_com_branch__bbfe26_idx'),
        ),
    ]
