# Generated by Django 5.2.17 on 2026-09-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SERVICES', 'Serviços'), ('PRODUCTS', 'Produtos'), ('SUBSCRIPTION', 'Planos mensais'), ('SALARY', 'Salários'), ('COMMISSION', 'Comissões'), ('RENT', 'Aluguel'), ('ELECTRICITY', 'Energia elétrica'), ('WATER', 'Água'), ('INTERNET', 'Internet'), ('SUPPLIES', 'Insumos'), ('MARKETING', 'Marketing'), ('TAXES', 'Impostos'), ('OTHER', 'Outros')], db_index=True, default='OTHER', max_length=15, verbose_name='categoria'),
        ),
    ]
