# Generated by Django 5.2.17 on 2026-09-03 14:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clients', '0001_initial'),
        ('inventory', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('balance', models.IntegerField(default=0, verbose_name='saldo de pontos')),
                ('lifetime_earned', models.IntegerField(default=0, verbose_name='pontos acumulados (total)')),
                ('lifetime_redeemed', models.IntegerField(default=0, verbose_name='pontos resgatados (total)')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='clients.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'conta de fidelidade',
                'verbose_name_plural': 'contas de fidelidade',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('type', models.CharField(choices=[('DISCOUNT_FIXED', 'Desconto em reais'), ('DISCOUNT_PERCENT', 'Desconto percentual'), ('FREE_SERVICE', 'Serviço gratuito')], default='DISCOUNT_FIXED', max_length=20, verbose_name='tipo')),
                ('points_cost', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='custo em pontos')),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor do desconto')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válida até')),
                ('service', models.ForeignKey(blank=True, help_text='Obrigatório quando o tipo é serviço gratuito.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_rewards', to='services.service', verbose_name='serviço')),
            ],
            options={
                'verbose_name': 'recompensa',
                'verbose_name_plural': 'recompensas',
                'ordering': ('points_cost',),
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('type', models.CharField(choices=[('EARN', 'Acúmulo'), ('REDEEM', 'Resgate'), ('ADJUSTMENT', 'Ajuste'), ('EXPIRED', 'Expiração')], max_length=12, verbose_name='tipo')),
                ('points', models.IntegerField(verbose_name='pontos')),
                ('balance_after', models.IntegerField(default=0, verbose_name='saldo após')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount', verbose_name='conta')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='appointments.appointment', verbose_name='agendamento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='loyalty.loyaltyreward', verbose_name='recompensa')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='inventory.sale', verbose_name='venda')),
            ],
            options={
                'verbose_name': 'movimento de fidelidade',
                'verbose_name_plural': 'movimentos de fidelidade',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='loyaltyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='loyaltyaccount_balance_not_negative'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['account', '-created_at'], name='loyalty_loy_account_383e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['type', '-created_at'], name='loyalty_loy_type_cafd1d_idx'),
        ),
    ]
