# Generated by Django 5.2.17 on 2026-09-04 23:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('logo', models.ImageField(blank=True, help_text='PNG com fundo transparente, idealmente 600x160 px.', null=True, upload_to='branding/', verbose_name='logo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branding_updates', to=settings.AUTH_USER_MODEL, verbose_name='atualizada por')),
            ],
            options={
                'verbose_name': 'identidade visual',
                'verbose_name_plural': 'identidade visual',
            },
        ),
    ]
