# Generated by Django 5.2.17 on 2026-09-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='company_name',
            field=models.CharField(default='Sua Barbearia', help_text='Exibido na marca do aplicativo e no título da página.', max_length=60, verbose_name='nome da barbearia'),
        ),
    ]
