# Generated by Django 5.2.17 on 2026-09-03 14:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('branches', '0001_initial'),
        ('clients', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='desconto')),
                ('method', models.CharField(choices=[('PIX', 'PIX'), ('CASH', 'Dinheiro'), ('CREDIT_CARD', 'Cartão de crédito'), ('DEBIT_CARD', 'Cartão de débito'), ('LOYALTY', 'Pontos de fidelidade'), ('OTHER', 'Outro')], max_length=15, verbose_name='forma de pagamento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Estornado')], db_index=True, default='PENDING', max_length=10, verbose_name='status')),
                ('provider', models.CharField(choices=[('MANUAL', 'Manual / caixa'), ('MERCADO_PAGO', 'Mercado Pago'), ('STRIPE', 'Stripe'), ('ASAAS', 'Asaas')], default='MANUAL', max_length=20, verbose_name='provedor')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='id externo')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='retorno do provedor')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='pago em')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='estornado em')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='observação')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='appointments.appointment', verbose_name='agendamento')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='branches.branch', verbose_name='filial')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='clients.client', verbose_name='cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_payments', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.sale', verbose_name='venda')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['branch', 'status', '-paid_at'], name='payments_pa_branch__a7054c_idx'), models.Index(fields=['method', '-paid_at'], name='payments_pa_method_385645_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('appointment__isnull', False), ('sale__isnull', False), _connector='OR'), name='payment_requires_appointment_or_sale')],
            },
        ),
    ]
