# Generated by Django 5.2.17 on 2026-09-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('PIX', 'PIX'), ('CASH', 'Dinheiro'), ('CREDIT_CARD', 'Cartão de crédito'), ('DEBIT_CARD', 'Cartão de débito'), ('LOYALTY', 'Pontos de fidelidade'), ('SUBSCRIPTION', 'Plano mensal'), ('OTHER', 'Outro')], max_length=15, verbose_name='forma de pagamento'),
        ),
    ]
