# Generated by Django 5.2.17 on 2026-09-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MANUAL', 'Manual / caixa'), ('STRIPE', 'Stripe'), ('ASAAS', 'Asaas')], default='MANUAL', max_length=20, verbose_name='provedor'),
        ),
    ]
