# Generated by Django 5.2.17 on 2026-09-04 17:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('branches', '0001_initial'),
        ('clients', '0001_initial'),
        ('finance', '0002_alter_transaction_category'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='mensalidade')),
                ('overage_discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desconto aplicado ao serviço quando a cota do ciclo já foi usada.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='desconto acima da cota')),
                ('pays_barber_commission', models.BooleanField(default=True, help_text='Quando ligado, o atendimento coberto pelo plano gera comissão sobre o preço do serviço, mesmo o cliente não pagando nada no balcão.', verbose_name='paga comissão ao barbeiro')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('is_public', models.BooleanField(default=True, help_text='Desligue para manter o plano apenas para assinatura manual.', verbose_name='visível ao cliente')),
                ('branches', models.ManyToManyField(blank=True, help_text='Filiais onde o plano é válido. Vazio significa todas.', related_name='plans', to='branches.branch', verbose_name='filiais')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ('price', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PlanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_quota', models.PositiveSmallIntegerField(default=1, help_text='Quantos usos por ciclo. Zero significa ilimitado.', verbose_name='cota mensal')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_services', to='plans.plan', verbose_name='plano')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_services', to='services.service', verbose_name='serviço')),
            ],
            options={
                'verbose_name': 'serviço do plano',
                'verbose_name_plural': 'serviços do plano',
                'ordering': ('plan', 'service'),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Aguardando pagamento'), ('ACTIVE', 'Ativa'), ('PAST_DUE', 'Pagamento atrasado'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], db_index=True, default='PENDING_PAYMENT', max_length=20, verbose_name='status')),
                ('billing_type', models.CharField(choices=[('CARD_RECURRING', 'Cartão de crédito (recorrente)'), ('PIX_MONTHLY', 'PIX (mês a mês)')], max_length=20, verbose_name='forma de cobrança')),
                ('price', models.DecimalField(decimal_places=2, help_text='Copiada do plano na assinatura: reajustes não afetam quem já assinou.', max_digits=10, verbose_name='mensalidade contratada')),
                ('current_period_start', models.DateField(blank=True, null=True, verbose_name='início do ciclo')),
                ('current_period_end', models.DateField(blank=True, db_index=True, null=True, verbose_name='fim do ciclo')),
                ('provider', models.CharField(choices=[('MANUAL', 'Manual / caixa'), ('MERCADO_PAGO', 'Mercado Pago'), ('STRIPE', 'Stripe'), ('ASAAS', 'Asaas')], default='MANUAL', max_length=20, verbose_name='provedor')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='`preapproval_id` no Mercado Pago, quando a cobrança é recorrente.', max_length=120, verbose_name='id externo')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='retorno do provedor')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='ativada em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='O cliente cancelou mas segue com o benefício até o ciclo pago terminar.', verbose_name='cancelar no fim do ciclo')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='observação')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='branches.branch', verbose_name='filial de preferência')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='clients.client', verbose_name='cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan', verbose_name='plano')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('period_start', models.DateField(verbose_name='início do ciclo')),
                ('period_end', models.DateField(verbose_name='fim do ciclo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor')),
                ('method', models.CharField(max_length=15, verbose_name='forma de pagamento')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando pagamento'), ('PAID', 'Paga'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada'), ('REFUNDED', 'Estornada')], db_index=True, default='PENDING', max_length=10, verbose_name='status')),
                ('due_date', models.DateField(db_index=True, verbose_name='vencimento')),
                ('provider', models.CharField(choices=[('MANUAL', 'Manual / caixa'), ('MERCADO_PAGO', 'Mercado Pago'), ('STRIPE', 'Stripe'), ('ASAAS', 'Asaas')], default='MANUAL', max_length=20, verbose_name='provedor')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='id externo')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='retorno do provedor')),
                ('pix_qr_code', models.TextField(blank=True, verbose_name='PIX copia e cola')),
                ('pix_qr_code_base64', models.TextField(blank=True, verbose_name='QR code (base64)')),
                ('checkout_url', models.URLField(blank=True, max_length=500, verbose_name='url de checkout')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='paga em')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_subscription_invoices', to=settings.AUTH_USER_MODEL, verbose_name='confirmada por')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='plans.subscription', verbose_name='assinatura')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_invoices', to='finance.transaction', verbose_name='lançamento no caixa')),
            ],
            options={
                'verbose_name': 'fatura de assinatura',
                'verbose_name_plural': 'faturas de assinatura',
                'ordering': ('-period_start', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True, verbose_name='ciclo')),
                ('covered_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor coberto')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='usado em')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_usage', to='appointments.appointment', verbose_name='atendimento')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_usages', to='services.service', verbose_name='serviço')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='plans.subscription', verbose_name='assinatura')),
            ],
            options={
                'verbose_name': 'uso do plano',
                'verbose_name_plural': 'usos do plano',
                'ordering': ('-used_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_plan_name'),
        ),
        migrations.AddConstraint(
            model_name='planservice',
            constraint=models.UniqueConstraint(fields=('plan', 'service'), name='unique_planservice_plan_service'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='plans_subsc_status_22a11c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan', 'status'], name='plans_subsc_plan_id_fe42c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING_PAYMENT', 'ACTIVE', 'PAST_DUE'))), fields=('client',), name='unique_live_subscription_per_client'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['status', 'due_date'], name='plans_subsc_status_5e9f7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'PAID'))), fields=('subscription', 'period_start'), name='unique_open_invoice_per_period'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='invoice_period_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusage',
            index=models.Index(fields=['subscription', 'period_start', 'service'], name='plans_subsc_subscri_d70ee2_idx'),
        ),
    ]
