# Generated by Django 5.2.17 on 2026-09-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='Id da assinatura no Asaas, quando a cobrança é recorrente.', max_length=120, verbose_name='id externo'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(choices=[('MANUAL', 'Manual / caixa'), ('STRIPE', 'Stripe'), ('ASAAS', 'Asaas')], default='MANUAL', max_length=20, verbose_name='provedor'),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='provider',
            field=models.CharField(choices=[('MANUAL', 'Manual / caixa'), ('STRIPE', 'Stripe'), ('ASAAS', 'Asaas')], default='MANUAL', max_length=20, verbose_name='provedor'),
        ),
    ]
