# Generated by Django 5.2.17 on 2026-09-03 14:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
        ('branches', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=11, verbose_name='CPF')),
                ('notes', models.TextField(blank=True, verbose_name='observações internas')),
                ('accepts_marketing', models.BooleanField(default=True, verbose_name='aceita comunicações')),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='pontos de fidelidade')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='total de visitas')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total gasto')),
                ('last_visit_at', models.DateTimeField(blank=True, null=True, verbose_name='último atendimento')),
                ('favorite_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_of_clients', to='services.service', verbose_name='serviço favorito')),
                ('preferred_barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_clients', to='barbers.barber', verbose_name='barbeiro preferido')),
                ('preferred_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_clients', to='branches.branch', verbose_name='filial preferida')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('user__first_name',),
                'indexes': [models.Index(fields=['preferred_branch', '-last_visit_at'], name='clients_cli_preferr_fda109_idx')],
            },
        ),
    ]
