# Generated by Django 5.2.17 on 2026-09-03 14:26

import apps.branches.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=14, verbose_name='CNPJ')),
                ('address', models.CharField(max_length=200, verbose_name='endereço')),
                ('number', models.CharField(max_length=20, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('district', models.CharField(max_length=100, verbose_name='bairro')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='estado')),
                ('zip_code', models.CharField(max_length=8, verbose_name='CEP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.branches.models.branch_cover_path, verbose_name='imagem de capa')),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(default=30, help_text='Granularidade da grade de horários exibida ao cliente.', validators=[django.core.validators.MinValueValidator(5)], verbose_name='intervalo entre horários (min)')),
                ('cancellation_limit_hours', models.PositiveSmallIntegerField(default=2, help_text='Antecedência mínima para o cliente cancelar sem penalidade.', verbose_name='limite para cancelamento (horas)')),
                ('max_advance_booking_days', models.PositiveSmallIntegerField(default=90, verbose_name='antecedência máxima de agendamento (dias)')),
                ('loyalty_points_per_currency_unit', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='pontos por R$ 1,00')),
                ('loyalty_point_value', models.DecimalField(decimal_places=4, default=Decimal('0.0400'), max_digits=6, verbose_name='valor de 1 ponto (R$)')),
            ],
            options={
                'verbose_name': 'filial',
                'verbose_name_plural': 'filiais',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['city', 'is_active'], name='branches_br_city_4f1cf8_idx')],
            },
        ),
        migrations.CreateModel(
            name='BranchHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='data')),
                ('description', models.CharField(max_length=120, verbose_name='descrição')),
                ('opens_at', models.TimeField(blank=True, null=True, verbose_name='abre às')),
                ('closes_at', models.TimeField(blank=True, null=True, verbose_name='fecha às')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='branches.branch', verbose_name='filial')),
            ],
            options={
                'verbose_name': 'feriado da filial',
                'verbose_name_plural': 'feriados da filial',
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('branch', 'date'), name='unique_holiday_branch_date')],
            },
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='dia da semana')),
                ('opens_at', models.TimeField(verbose_name='abre às')),
                ('closes_at', models.TimeField(verbose_name='fecha às')),
                ('is_closed', models.BooleanField(default=False, verbose_name='fechado')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='branches.branch', verbose_name='filial')),
            ],
            options={
                'verbose_name': 'horário de funcionamento',
                'verbose_name_plural': 'horários de funcionamento',
                'ordering': ('branch', 'weekday', 'opens_at'),
                'constraints': [models.UniqueConstraint(fields=('branch', 'weekday'), name='unique_openinghour_branch_weekday'), models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='openinghour_closes_after_opens')],
            },
        ),
    ]
