# Generated by Django 5.2.17 on 2026-09-03 14:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('barbers', '0001_initial'),
        ('branches', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='nota')),
                ('comment', models.TextField(blank=True, verbose_name='comentário')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicada')),
                ('reply', models.TextField(blank=True, verbose_name='resposta da barbearia')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='respondida em')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='appointments.appointment', verbose_name='agendamento')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='barbers.barber', verbose_name='barbeiro')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='branches.branch', verbose_name='filial')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clients.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['barber', '-created_at'], name='reviews_rev_barber__179cca_idx'), models.Index(fields=['branch', 'rating'], name='reviews_rev_branch__364c5d_idx')],
            },
        ),
    ]
