# Generated by Django 5.2.17 on 2026-09-03 14:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
        ('branches', '0001_initial'),
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('date', models.DateField(db_index=True, verbose_name='data')),
                ('start_time', models.TimeField(verbose_name='início')),
                ('end_time', models.TimeField(verbose_name='fim')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('ARRIVED', 'Cliente chegou'), ('IN_PROGRESS', 'Em atendimento'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado'), ('NO_SHOW', 'Não compareceu')], db_index=True, default='PENDING', max_length=12, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('internal_notes', models.TextField(blank=True, verbose_name='observações internas')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='chegada do cliente')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='início do atendimento')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='conclusão')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('cancelled_by_role', models.CharField(blank=True, choices=[('CLIENT', 'Cliente'), ('BARBER', 'Barbeiro'), ('OWNER', 'Proprietário'), ('SYSTEM', 'Sistema')], max_length=10, verbose_name='cancelado por')),
                ('cancellation_reason', models.CharField(blank=True, max_length=300, verbose_name='motivo do cancelamento')),
                ('reminders_sent', models.JSONField(blank=True, default=list, verbose_name='lembretes enviados')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='barbers.barber', verbose_name='barbeiro')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='branches.branch', verbose_name='filial')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL, verbose_name='usuário que cancelou')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clients.client', verbose_name='cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedules', to='appointments.appointment', verbose_name='reagendado a partir de')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service', verbose_name='serviço')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'ordering': ('-date', '-start_time'),
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('ARRIVED', 'Cliente chegou'), ('IN_PROGRESS', 'Em atendimento'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado'), ('NO_SHOW', 'Não compareceu')], max_length=12, verbose_name='de')),
                ('to_status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('ARRIVED', 'Cliente chegou'), ('IN_PROGRESS', 'Em atendimento'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado'), ('NO_SHOW', 'Não compareceu')], max_length=12, verbose_name='para')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='motivo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='appointments.appointment', verbose_name='agendamento')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'histórico do agendamento',
                'verbose_name_plural': 'históricos do agendamento',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['branch', 'date', 'status'], name='appointment_branch__47569b_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['barber', 'date', 'start_time'], name='appointment_barber__3d4991_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', '-date'], name='appointment_client__637440_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'date'], name='appointment_status_53df83_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='appointment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'ARRIVED', 'IN_PROGRESS'])), fields=('barber', 'date', 'start_time'), name='unique_active_appointment_per_barber_slot'),
        ),
    ]
