# Generated by Django 5.2.17 on 2026-09-03 14:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='token')),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], max_length=10, verbose_name='plataforma')),
                ('device_name', models.CharField(blank=True, max_length=120, verbose_name='dispositivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='último uso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'token de dispositivo',
                'verbose_name_plural': 'tokens de dispositivo',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('type', models.CharField(choices=[('APPOINTMENT_CREATED', 'Agendamento criado'), ('APPOINTMENT_CONFIRMED', 'Agendamento confirmado'), ('APPOINTMENT_REMINDER', 'Lembrete de agendamento'), ('APPOINTMENT_CANCELLED', 'Agendamento cancelado'), ('APPOINTMENT_RESCHEDULED', 'Agendamento remarcado'), ('APPOINTMENT_COMPLETED', 'Atendimento concluído'), ('LOYALTY', 'Fidelidade'), ('PROMOTION', 'Promoção'), ('SYSTEM', 'Sistema')], max_length=25, verbose_name='tipo')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('body', models.TextField(verbose_name='mensagem')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='dados')),
                ('channels', models.JSONField(blank=True, default=list, verbose_name='canais')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lida em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment', verbose_name='agendamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
            },
        ),
    ]
